<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Domain\Manga\Models\Genre;
use Illuminate\Database\Seeder;

/**
 * Seeds common manga genres.
 *
 * Why these 15 genres?
 * - Most popular/common genres found on major manga sites
 * - Covers broad range: demographics (Shounen/Seinen/Shoujo)
 *   and themes (Action, Romance, Isekai, etc.)
 *
 * Slug is auto-generated by Spatie Sluggable.
 */
class GenreSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // List of 15 common manga genres
        // Ordered alphabetically for consistency
        $genres = [
            'Action',
            'Adventure',
            'Comedy',
            'Drama',
            'Fantasy',
            'Horror',
            'Isekai',
            'Mystery',
            'Romance',
            'Sci-Fi',
            'Seinen',
            'Shoujo',
            'Shounen',
            'Slice of Life',
            'Supernatural',
        ];

        foreach ($genres as $name) {
            // Slug auto-generated by HasSlug trait
            // e.g., "Slice of Life" -> "slice-of-life"
            Genre::create(['name' => $name]);
        }
    }
}
